---
# config file version
#apiVersion: 1

# list of datasources that should be deleted from the database
#deleteDatasources:
#  - name: Graphite
#    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: Loki
    type: loki
    orgId: 2
    uid: loki
    url: http://loki:3100
    isDefault: false
    version: 1
    editable: true